//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoudizhuClient.DoudizhuService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="DoudizhuServiceContract")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="DoudizhuServiceContract")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoudizhuClient.DoudizhuService.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFreeGiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LandlordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoudizhuClient.DoudizhuService.Card[] LastCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoudizhuClient.DoudizhuService.Card[] LeftCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadyForLandlordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoudizhuClient.DoudizhuService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFreeGive {
            get {
                return this.IsFreeGiveField;
            }
            set {
                if ((this.IsFreeGiveField.Equals(value) != true)) {
                    this.IsFreeGiveField = value;
                    this.RaisePropertyChanged("IsFreeGive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Landlord {
            get {
                return this.LandlordField;
            }
            set {
                if ((this.LandlordField.Equals(value) != true)) {
                    this.LandlordField = value;
                    this.RaisePropertyChanged("Landlord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoudizhuClient.DoudizhuService.Card[] LastCards {
            get {
                return this.LastCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.LastCardsField, value) != true)) {
                    this.LastCardsField = value;
                    this.RaisePropertyChanged("LastCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoudizhuClient.DoudizhuService.Card[] LeftCards {
            get {
                return this.LeftCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftCardsField, value) != true)) {
                    this.LeftCardsField = value;
                    this.RaisePropertyChanged("LeftCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextPlayer {
            get {
                return this.NextPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.NextPlayerField, value) != true)) {
                    this.NextPlayerField = value;
                    this.RaisePropertyChanged("NextPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousPlayer {
            get {
                return this.PreviousPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousPlayerField, value) != true)) {
                    this.PreviousPlayerField = value;
                    this.RaisePropertyChanged("PreviousPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ready {
            get {
                return this.ReadyField;
            }
            set {
                if ((this.ReadyField.Equals(value) != true)) {
                    this.ReadyField = value;
                    this.RaisePropertyChanged("Ready");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReadyForLandlord {
            get {
                return this.ReadyForLandlordField;
            }
            set {
                if ((this.ReadyForLandlordField.Equals(value) != true)) {
                    this.ReadyForLandlordField = value;
                    this.RaisePropertyChanged("ReadyForLandlord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="DoudizhuServiceContract")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Friend {
            get {
                return this.FriendField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendField, value) != true)) {
                    this.FriendField = value;
                    this.RaisePropertyChanged("Friend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMale {
            get {
                return this.IsMaleField;
            }
            set {
                if ((this.IsMaleField.Equals(value) != true)) {
                    this.IsMaleField = value;
                    this.RaisePropertyChanged("IsMale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerImage {
            get {
                return this.PlayerImageField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerImageField, value) != true)) {
                    this.PlayerImageField = value;
                    this.RaisePropertyChanged("PlayerImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IDoudizhuService")]
    public interface IDoudizhuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/LoadLobby", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LoadLobbyResponse")]
        void LoadLobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/LoadLobby", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LoadLobbyResponse")]
        System.Threading.Tasks.Task LoadLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/UpdateLobby", ReplyAction="DoudizhuServiceContract/IDoudizhuService/UpdateLobbyResponse")]
        void UpdateLobby(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/UpdateLobby", ReplyAction="DoudizhuServiceContract/IDoudizhuService/UpdateLobbyResponse")]
        System.Threading.Tasks.Task UpdateLobbyAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SetPlayerReady", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SetPlayerReadyResponse")]
        void SetPlayerReady(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SetPlayerReady", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SetPlayerReadyResponse")]
        System.Threading.Tasks.Task SetPlayerReadyAsync(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SetPlayerWait", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SetPlayerWaitResponse")]
        void SetPlayerWait(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SetPlayerWait", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SetPlayerWaitResponse")]
        System.Threading.Tasks.Task SetPlayerWaitAsync(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Register", ReplyAction="DoudizhuServiceContract/IDoudizhuService/RegisterResponse")]
        bool Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Register", ReplyAction="DoudizhuServiceContract/IDoudizhuService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Login", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LoginResponse")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Login", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Logout", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LogoutResponse")]
        void Logout(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/Logout", ReplyAction="DoudizhuServiceContract/IDoudizhuService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/CreateRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/CreateRoomResponse")]
        void CreateRoom(int roomNumber, int baseScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/CreateRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/CreateRoomResponse")]
        System.Threading.Tasks.Task CreateRoomAsync(int roomNumber, int baseScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerJoinRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerJoinRoomResponse")]
        void PlayerJoinRoom(string username, int roomNumber, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerJoinRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerJoinRoomResponse")]
        System.Threading.Tasks.Task PlayerJoinRoomAsync(string username, int roomNumber, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerLeaveRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerLeaveRoomResponse")]
        void PlayerLeaveRoom(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerLeaveRoom", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerLeaveRoomResponse")]
        System.Threading.Tasks.Task PlayerLeaveRoomAsync(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/DetermindLandlord", ReplyAction="DoudizhuServiceContract/IDoudizhuService/DetermindLandlordResponse")]
        void DetermindLandlord(string username, bool l, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/DetermindLandlord", ReplyAction="DoudizhuServiceContract/IDoudizhuService/DetermindLandlordResponse")]
        System.Threading.Tasks.Task DetermindLandlordAsync(string username, bool l, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetBetNumber", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetBetNumberResponse")]
        int GetBetNumber(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetBetNumber", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetBetNumberResponse")]
        System.Threading.Tasks.Task<int> GetBetNumberAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetBaseScore", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetBaseScoreResponse")]
        int GetBaseScore(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetBaseScore", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetBaseScoreResponse")]
        System.Threading.Tasks.Task<int> GetBaseScoreAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetLeftoverCards", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetLeftoverCardsResponse")]
        DoudizhuClient.DoudizhuService.Card[] GetLeftoverCards(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetLeftoverCards", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetLeftoverCardsResponse")]
        System.Threading.Tasks.Task<DoudizhuClient.DoudizhuService.Card[]> GetLeftoverCardsAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/StartDetermineLandlord", ReplyAction="DoudizhuServiceContract/IDoudizhuService/StartDetermineLandlordResponse")]
        void StartDetermineLandlord(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/StartDetermineLandlord", ReplyAction="DoudizhuServiceContract/IDoudizhuService/StartDetermineLandlordResponse")]
        System.Threading.Tasks.Task StartDetermineLandlordAsync(string username, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GiveCards", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GiveCardsResponse")]
        void GiveCards(string username, int[] index, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GiveCards", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GiveCardsResponse")]
        System.Threading.Tasks.Task GiveCardsAsync(string username, int[] index, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/ValidateCardsCombination", ReplyAction="DoudizhuServiceContract/IDoudizhuService/ValidateCardsCombinationResponse")]
        bool ValidateCardsCombination(string username, int[] cards, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/ValidateCardsCombination", ReplyAction="DoudizhuServiceContract/IDoudizhuService/ValidateCardsCombinationResponse")]
        System.Threading.Tasks.Task<bool> ValidateCardsCombinationAsync(string username, int[] cards, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/ValidateCardsComparison", ReplyAction="DoudizhuServiceContract/IDoudizhuService/ValidateCardsComparisonResponse")]
        bool ValidateCardsComparison(string username, int[] cards, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/ValidateCardsComparison", ReplyAction="DoudizhuServiceContract/IDoudizhuService/ValidateCardsComparisonResponse")]
        System.Threading.Tasks.Task<bool> ValidateCardsComparisonAsync(string username, int[] cards, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GiveHints", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GiveHintsResponse")]
        int[] GiveHints(string usename, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GiveHints", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GiveHintsResponse")]
        System.Threading.Tasks.Task<int[]> GiveHintsAsync(string usename, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetPlayerByUsername", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetPlayerByUsernameResponse")]
        DoudizhuClient.DoudizhuService.Player GetPlayerByUsername(string usename, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/GetPlayerByUsername", ReplyAction="DoudizhuServiceContract/IDoudizhuService/GetPlayerByUsernameResponse")]
        System.Threading.Tasks.Task<DoudizhuClient.DoudizhuService.Player> GetPlayerByUsernameAsync(string usename, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SendMessage", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SendMessageResponse")]
        void SendMessage(string playername, string message, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/SendMessage", ReplyAction="DoudizhuServiceContract/IDoudizhuService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string playername, string message, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerQuit", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerQuitResponse")]
        void PlayerQuit(string playername, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/PlayerQuit", ReplyAction="DoudizhuServiceContract/IDoudizhuService/PlayerQuitResponse")]
        System.Threading.Tasks.Task PlayerQuitAsync(string playername, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/InGame", ReplyAction="DoudizhuServiceContract/IDoudizhuService/InGameResponse")]
        bool InGame(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDoudizhuService/InGame", ReplyAction="DoudizhuServiceContract/IDoudizhuService/InGameResponse")]
        System.Threading.Tasks.Task<bool> InGameAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoudizhuServiceChannel : DoudizhuClient.DoudizhuService.IDoudizhuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoudizhuServiceClient : System.ServiceModel.ClientBase<DoudizhuClient.DoudizhuService.IDoudizhuService>, DoudizhuClient.DoudizhuService.IDoudizhuService {
        
        public DoudizhuServiceClient() {
        }
        
        public DoudizhuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoudizhuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoudizhuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoudizhuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LoadLobby() {
            base.Channel.LoadLobby();
        }
        
        public System.Threading.Tasks.Task LoadLobbyAsync() {
            return base.Channel.LoadLobbyAsync();
        }
        
        public void UpdateLobby(int roomNumber) {
            base.Channel.UpdateLobby(roomNumber);
        }
        
        public System.Threading.Tasks.Task UpdateLobbyAsync(int roomNumber) {
            return base.Channel.UpdateLobbyAsync(roomNumber);
        }
        
        public void SetPlayerReady(string username, int roomNumber) {
            base.Channel.SetPlayerReady(username, roomNumber);
        }
        
        public System.Threading.Tasks.Task SetPlayerReadyAsync(string username, int roomNumber) {
            return base.Channel.SetPlayerReadyAsync(username, roomNumber);
        }
        
        public void SetPlayerWait(string username, int roomNumber) {
            base.Channel.SetPlayerWait(username, roomNumber);
        }
        
        public System.Threading.Tasks.Task SetPlayerWaitAsync(string username, int roomNumber) {
            return base.Channel.SetPlayerWaitAsync(username, roomNumber);
        }
        
        public bool Register(string username, string password) {
            return base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Logout(string username) {
            base.Channel.Logout(username);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string username) {
            return base.Channel.LogoutAsync(username);
        }
        
        public void CreateRoom(int roomNumber, int baseScore) {
            base.Channel.CreateRoom(roomNumber, baseScore);
        }
        
        public System.Threading.Tasks.Task CreateRoomAsync(int roomNumber, int baseScore) {
            return base.Channel.CreateRoomAsync(roomNumber, baseScore);
        }
        
        public void PlayerJoinRoom(string username, int roomNumber, int position) {
            base.Channel.PlayerJoinRoom(username, roomNumber, position);
        }
        
        public System.Threading.Tasks.Task PlayerJoinRoomAsync(string username, int roomNumber, int position) {
            return base.Channel.PlayerJoinRoomAsync(username, roomNumber, position);
        }
        
        public void PlayerLeaveRoom(string username, int roomNumber) {
            base.Channel.PlayerLeaveRoom(username, roomNumber);
        }
        
        public System.Threading.Tasks.Task PlayerLeaveRoomAsync(string username, int roomNumber) {
            return base.Channel.PlayerLeaveRoomAsync(username, roomNumber);
        }
        
        public void DetermindLandlord(string username, bool l, int roomNumber) {
            base.Channel.DetermindLandlord(username, l, roomNumber);
        }
        
        public System.Threading.Tasks.Task DetermindLandlordAsync(string username, bool l, int roomNumber) {
            return base.Channel.DetermindLandlordAsync(username, l, roomNumber);
        }
        
        public int GetBetNumber(int roomNumber) {
            return base.Channel.GetBetNumber(roomNumber);
        }
        
        public System.Threading.Tasks.Task<int> GetBetNumberAsync(int roomNumber) {
            return base.Channel.GetBetNumberAsync(roomNumber);
        }
        
        public int GetBaseScore(int roomNumber) {
            return base.Channel.GetBaseScore(roomNumber);
        }
        
        public System.Threading.Tasks.Task<int> GetBaseScoreAsync(int roomNumber) {
            return base.Channel.GetBaseScoreAsync(roomNumber);
        }
        
        public DoudizhuClient.DoudizhuService.Card[] GetLeftoverCards(int roomNumber) {
            return base.Channel.GetLeftoverCards(roomNumber);
        }
        
        public System.Threading.Tasks.Task<DoudizhuClient.DoudizhuService.Card[]> GetLeftoverCardsAsync(int roomNumber) {
            return base.Channel.GetLeftoverCardsAsync(roomNumber);
        }
        
        public void StartDetermineLandlord(string username, int roomNumber) {
            base.Channel.StartDetermineLandlord(username, roomNumber);
        }
        
        public System.Threading.Tasks.Task StartDetermineLandlordAsync(string username, int roomNumber) {
            return base.Channel.StartDetermineLandlordAsync(username, roomNumber);
        }
        
        public void GiveCards(string username, int[] index, int roomNumber) {
            base.Channel.GiveCards(username, index, roomNumber);
        }
        
        public System.Threading.Tasks.Task GiveCardsAsync(string username, int[] index, int roomNumber) {
            return base.Channel.GiveCardsAsync(username, index, roomNumber);
        }
        
        public bool ValidateCardsCombination(string username, int[] cards, int roomNumber) {
            return base.Channel.ValidateCardsCombination(username, cards, roomNumber);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCardsCombinationAsync(string username, int[] cards, int roomNumber) {
            return base.Channel.ValidateCardsCombinationAsync(username, cards, roomNumber);
        }
        
        public bool ValidateCardsComparison(string username, int[] cards, int roomNumber) {
            return base.Channel.ValidateCardsComparison(username, cards, roomNumber);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCardsComparisonAsync(string username, int[] cards, int roomNumber) {
            return base.Channel.ValidateCardsComparisonAsync(username, cards, roomNumber);
        }
        
        public int[] GiveHints(string usename, int roomNumber) {
            return base.Channel.GiveHints(usename, roomNumber);
        }
        
        public System.Threading.Tasks.Task<int[]> GiveHintsAsync(string usename, int roomNumber) {
            return base.Channel.GiveHintsAsync(usename, roomNumber);
        }
        
        public DoudizhuClient.DoudizhuService.Player GetPlayerByUsername(string usename, int roomNumber) {
            return base.Channel.GetPlayerByUsername(usename, roomNumber);
        }
        
        public System.Threading.Tasks.Task<DoudizhuClient.DoudizhuService.Player> GetPlayerByUsernameAsync(string usename, int roomNumber) {
            return base.Channel.GetPlayerByUsernameAsync(usename, roomNumber);
        }
        
        public void SendMessage(string playername, string message, int roomNumber) {
            base.Channel.SendMessage(playername, message, roomNumber);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string playername, string message, int roomNumber) {
            return base.Channel.SendMessageAsync(playername, message, roomNumber);
        }
        
        public void PlayerQuit(string playername, int roomNumber) {
            base.Channel.PlayerQuit(playername, roomNumber);
        }
        
        public System.Threading.Tasks.Task PlayerQuitAsync(string playername, int roomNumber) {
            return base.Channel.PlayerQuitAsync(playername, roomNumber);
        }
        
        public bool InGame(int roomNumber) {
            return base.Channel.InGame(roomNumber);
        }
        
        public System.Threading.Tasks.Task<bool> InGameAsync(int roomNumber) {
            return base.Channel.InGameAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.ILoadLobby", CallbackContract=typeof(DoudizhuClient.DoudizhuService.ILoadLobbyCallback))]
    public interface ILoadLobby {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ILoadLobby/loadLobbySubscribe", ReplyAction="DoudizhuServiceContract/ILoadLobby/loadLobbySubscribeResponse")]
        void loadLobbySubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ILoadLobby/loadLobbySubscribe", ReplyAction="DoudizhuServiceContract/ILoadLobby/loadLobbySubscribeResponse")]
        System.Threading.Tasks.Task loadLobbySubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ILoadLobby/loadLobbyUnSubscribe", ReplyAction="DoudizhuServiceContract/ILoadLobby/loadLobbyUnSubscribeResponse")]
        void loadLobbyUnSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ILoadLobby/loadLobbyUnSubscribe", ReplyAction="DoudizhuServiceContract/ILoadLobby/loadLobbyUnSubscribeResponse")]
        System.Threading.Tasks.Task loadLobbyUnSubscribeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadLobbyCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/ILoadLobby/LoadLobby_Client")]
        void LoadLobby_Client(DoudizhuClient.DoudizhuService.Player p1, DoudizhuClient.DoudizhuService.Player p2, DoudizhuClient.DoudizhuService.Player p3, int roomNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadLobbyChannel : DoudizhuClient.DoudizhuService.ILoadLobby, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadLobbyClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.ILoadLobby>, DoudizhuClient.DoudizhuService.ILoadLobby {
        
        public LoadLobbyClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoadLobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoadLobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoadLobbyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoadLobbyClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void loadLobbySubscribe() {
            base.Channel.loadLobbySubscribe();
        }
        
        public System.Threading.Tasks.Task loadLobbySubscribeAsync() {
            return base.Channel.loadLobbySubscribeAsync();
        }
        
        public void loadLobbyUnSubscribe() {
            base.Channel.loadLobbyUnSubscribe();
        }
        
        public System.Threading.Tasks.Task loadLobbyUnSubscribeAsync() {
            return base.Channel.loadLobbyUnSubscribeAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.ISetCancelPlayerReady", CallbackContract=typeof(DoudizhuClient.DoudizhuService.ISetCancelPlayerReadyCallback))]
    public interface ISetCancelPlayerReady {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadySubscribe", ReplyAction="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadySubscribeRespon" +
            "se")]
        void playerSetCancelReadySubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadySubscribe", ReplyAction="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadySubscribeRespon" +
            "se")]
        System.Threading.Tasks.Task playerSetCancelReadySubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadyUnSubscribe", ReplyAction="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadyUnSubscribeResp" +
            "onse")]
        void playerSetCancelReadyUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadyUnSubscribe", ReplyAction="DoudizhuServiceContract/ISetCancelPlayerReady/playerSetCancelReadyUnSubscribeResp" +
            "onse")]
        System.Threading.Tasks.Task playerSetCancelReadyUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISetCancelPlayerReadyCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/ISetCancelPlayerReady/SetCancelPlayerReady_Client")]
        void SetCancelPlayerReady_Client(DoudizhuClient.DoudizhuService.Player p1, DoudizhuClient.DoudizhuService.Player p2, DoudizhuClient.DoudizhuService.Player p3, int roomNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISetCancelPlayerReadyChannel : DoudizhuClient.DoudizhuService.ISetCancelPlayerReady, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetCancelPlayerReadyClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.ISetCancelPlayerReady>, DoudizhuClient.DoudizhuService.ISetCancelPlayerReady {
        
        public SetCancelPlayerReadyClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SetCancelPlayerReadyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SetCancelPlayerReadyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SetCancelPlayerReadyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SetCancelPlayerReadyClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void playerSetCancelReadySubscribe(int roomNumber) {
            base.Channel.playerSetCancelReadySubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task playerSetCancelReadySubscribeAsync(int roomNumber) {
            return base.Channel.playerSetCancelReadySubscribeAsync(roomNumber);
        }
        
        public void playerSetCancelReadyUnSubscribe(int roomNumber) {
            base.Channel.playerSetCancelReadyUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task playerSetCancelReadyUnSubscribeAsync(int roomNumber) {
            return base.Channel.playerSetCancelReadyUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IPlayerJoinLeaveRoom", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IPlayerJoinLeaveRoomCallback))]
    public interface IPlayerJoinLeaveRoom {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomSubscribe", ReplyAction="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomSubscribeResponse" +
            "")]
        void playerJoinLeaveRoomSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomSubscribe", ReplyAction="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomSubscribeResponse" +
            "")]
        System.Threading.Tasks.Task playerJoinLeaveRoomSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomUnSubscribe", ReplyAction="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomUnSubscribeRespon" +
            "se")]
        void playerJoinLeaveRoomUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomUnSubscribe", ReplyAction="DoudizhuServiceContract/IPlayerJoinLeaveRoom/playerJoinLeaveRoomUnSubscribeRespon" +
            "se")]
        System.Threading.Tasks.Task playerJoinLeaveRoomUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerJoinLeaveRoomCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IPlayerJoinLeaveRoom/PlayerJoinLeaveRoom_Client")]
        void PlayerJoinLeaveRoom_Client(DoudizhuClient.DoudizhuService.Player p1, DoudizhuClient.DoudizhuService.Player p2, DoudizhuClient.DoudizhuService.Player p3, int roomNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerJoinLeaveRoomChannel : DoudizhuClient.DoudizhuService.IPlayerJoinLeaveRoom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerJoinLeaveRoomClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IPlayerJoinLeaveRoom>, DoudizhuClient.DoudizhuService.IPlayerJoinLeaveRoom {
        
        public PlayerJoinLeaveRoomClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerJoinLeaveRoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerJoinLeaveRoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerJoinLeaveRoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerJoinLeaveRoomClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void playerJoinLeaveRoomSubscribe(int roomNumber) {
            base.Channel.playerJoinLeaveRoomSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task playerJoinLeaveRoomSubscribeAsync(int roomNumber) {
            return base.Channel.playerJoinLeaveRoomSubscribeAsync(roomNumber);
        }
        
        public void playerJoinLeaveRoomUnSubscribe(int roomNumber) {
            base.Channel.playerJoinLeaveRoomUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task playerJoinLeaveRoomUnSubscribeAsync(int roomNumber) {
            return base.Channel.playerJoinLeaveRoomUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IStartGame", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IStartGameCallback))]
    public interface IStartGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IStartGame/startGameSubscribe", ReplyAction="DoudizhuServiceContract/IStartGame/startGameSubscribeResponse")]
        void startGameSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IStartGame/startGameSubscribe", ReplyAction="DoudizhuServiceContract/IStartGame/startGameSubscribeResponse")]
        System.Threading.Tasks.Task startGameSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IStartGame/startGameUnSubscribe", ReplyAction="DoudizhuServiceContract/IStartGame/startGameUnSubscribeResponse")]
        void startGameUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IStartGame/startGameUnSubscribe", ReplyAction="DoudizhuServiceContract/IStartGame/startGameUnSubscribeResponse")]
        System.Threading.Tasks.Task startGameUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartGameCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IStartGame/StartGame_Client")]
        void StartGame_Client(DoudizhuClient.DoudizhuService.Player p1, DoudizhuClient.DoudizhuService.Player p2, DoudizhuClient.DoudizhuService.Player p3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStartGameChannel : DoudizhuClient.DoudizhuService.IStartGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StartGameClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IStartGame>, DoudizhuClient.DoudizhuService.IStartGame {
        
        public StartGameClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public StartGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public StartGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StartGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StartGameClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void startGameSubscribe(int roomNumber) {
            base.Channel.startGameSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task startGameSubscribeAsync(int roomNumber) {
            return base.Channel.startGameSubscribeAsync(roomNumber);
        }
        
        public void startGameUnSubscribe(int roomNumber) {
            base.Channel.startGameUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task startGameUnSubscribeAsync(int roomNumber) {
            return base.Channel.startGameUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IDeterminteLandlord", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IDeterminteLandlordCallback))]
    public interface IDeterminteLandlord {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordSubscribe", ReplyAction="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordSubscribeResponse")]
        void determinteLandlordSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordSubscribe", ReplyAction="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordSubscribeResponse")]
        System.Threading.Tasks.Task determinteLandlordSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordUnSubscribe", ReplyAction="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordUnSubscribeResponse" +
            "")]
        void determinteLandlordUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordUnSubscribe", ReplyAction="DoudizhuServiceContract/IDeterminteLandlord/determinteLandlordUnSubscribeResponse" +
            "")]
        System.Threading.Tasks.Task determinteLandlordUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeterminteLandlordCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IDeterminteLandlord/DeterminteLandlord_Client")]
        void DeterminteLandlord_Client(DoudizhuClient.DoudizhuService.Player[] tempdizhu, bool[] dizhuorNot, DoudizhuClient.DoudizhuService.Player current, bool determined);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeterminteLandlordChannel : DoudizhuClient.DoudizhuService.IDeterminteLandlord, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeterminteLandlordClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IDeterminteLandlord>, DoudizhuClient.DoudizhuService.IDeterminteLandlord {
        
        public DeterminteLandlordClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DeterminteLandlordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DeterminteLandlordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DeterminteLandlordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DeterminteLandlordClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void determinteLandlordSubscribe(int roomNumber) {
            base.Channel.determinteLandlordSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task determinteLandlordSubscribeAsync(int roomNumber) {
            return base.Channel.determinteLandlordSubscribeAsync(roomNumber);
        }
        
        public void determinteLandlordUnSubscribe(int roomNumber) {
            base.Channel.determinteLandlordUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task determinteLandlordUnSubscribeAsync(int roomNumber) {
            return base.Channel.determinteLandlordUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IUpdateGame", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IUpdateGameCallback))]
    public interface IUpdateGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateGame/updateGameSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateGame/updateGameSubscribeResponse")]
        void updateGameSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateGame/updateGameSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateGame/updateGameSubscribeResponse")]
        System.Threading.Tasks.Task updateGameSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateGame/updateGameUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateGame/updateGameUnSubscribeResponse")]
        void updateGameUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateGame/updateGameUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateGame/updateGameUnSubscribeResponse")]
        System.Threading.Tasks.Task updateGameUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateGameCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IUpdateGame/UpdateGame_Client")]
        void UpdateGame_Client(DoudizhuClient.DoudizhuService.Player current, int bet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateGameChannel : DoudizhuClient.DoudizhuService.IUpdateGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateGameClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IUpdateGame>, DoudizhuClient.DoudizhuService.IUpdateGame {
        
        public UpdateGameClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UpdateGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UpdateGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateGameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateGameClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void updateGameSubscribe(int roomNumber) {
            base.Channel.updateGameSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateGameSubscribeAsync(int roomNumber) {
            return base.Channel.updateGameSubscribeAsync(roomNumber);
        }
        
        public void updateGameUnSubscribe(int roomNumber) {
            base.Channel.updateGameUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateGameUnSubscribeAsync(int roomNumber) {
            return base.Channel.updateGameUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.ITimeCounterDown", CallbackContract=typeof(DoudizhuClient.DoudizhuService.ITimeCounterDownCallback))]
    public interface ITimeCounterDown {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownSubscribe", ReplyAction="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownSubscribeResponse")]
        void timeCounterDownSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownSubscribe", ReplyAction="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownSubscribeResponse")]
        System.Threading.Tasks.Task timeCounterDownSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownUnSubscribe", ReplyAction="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownUnSubscribeResponse")]
        void timeCounterDownUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownUnSubscribe", ReplyAction="DoudizhuServiceContract/ITimeCounterDown/timeCounterDownUnSubscribeResponse")]
        System.Threading.Tasks.Task timeCounterDownUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeCounterDownCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/ITimeCounterDown/TimeCounterDown_Client")]
        void TimeCounterDown_Client(DoudizhuClient.DoudizhuService.Player current, int timeLeft);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeCounterDownChannel : DoudizhuClient.DoudizhuService.ITimeCounterDown, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeCounterDownClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.ITimeCounterDown>, DoudizhuClient.DoudizhuService.ITimeCounterDown {
        
        public TimeCounterDownClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TimeCounterDownClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TimeCounterDownClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TimeCounterDownClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TimeCounterDownClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void timeCounterDownSubscribe(int roomNumber) {
            base.Channel.timeCounterDownSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task timeCounterDownSubscribeAsync(int roomNumber) {
            return base.Channel.timeCounterDownSubscribeAsync(roomNumber);
        }
        
        public void timeCounterDownUnSubscribe(int roomNumber) {
            base.Channel.timeCounterDownUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task timeCounterDownUnSubscribeAsync(int roomNumber) {
            return base.Channel.timeCounterDownUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IGameOver", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IGameOverCallback))]
    public interface IGameOver {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IGameOver/gameoverSubscribe", ReplyAction="DoudizhuServiceContract/IGameOver/gameoverSubscribeResponse")]
        void gameoverSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IGameOver/gameoverSubscribe", ReplyAction="DoudizhuServiceContract/IGameOver/gameoverSubscribeResponse")]
        System.Threading.Tasks.Task gameoverSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IGameOver/gameoverUnSubscribe", ReplyAction="DoudizhuServiceContract/IGameOver/gameoverUnSubscribeResponse")]
        void gameoverUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IGameOver/gameoverUnSubscribe", ReplyAction="DoudizhuServiceContract/IGameOver/gameoverUnSubscribeResponse")]
        System.Threading.Tasks.Task gameoverUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameOverCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IGameOver/GameOver_Client")]
        void GameOver_Client(DoudizhuClient.DoudizhuService.Player previous, DoudizhuClient.DoudizhuService.Player winner, DoudizhuClient.DoudizhuService.Player next, DoudizhuClient.DoudizhuService.Card[] leftovercards, DoudizhuClient.DoudizhuService.Player quitter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameOverChannel : DoudizhuClient.DoudizhuService.IGameOver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameOverClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IGameOver>, DoudizhuClient.DoudizhuService.IGameOver {
        
        public GameOverClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameOverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameOverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameOverClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameOverClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void gameoverSubscribe(int roomNumber) {
            base.Channel.gameoverSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task gameoverSubscribeAsync(int roomNumber) {
            return base.Channel.gameoverSubscribeAsync(roomNumber);
        }
        
        public void gameoverUnSubscribe(int roomNumber) {
            base.Channel.gameoverUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task gameoverUnSubscribeAsync(int roomNumber) {
            return base.Channel.gameoverUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IUpdateLandlordCard", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IUpdateLandlordCardCallback))]
    public interface IUpdateLandlordCard {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardSubscribeResponse")]
        void updateLandlordCardSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardSubscribeResponse")]
        System.Threading.Tasks.Task updateLandlordCardSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardUnSubscribeResponse" +
            "")]
        void updateLandlordCardUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateLandlordCard/updateLandlordCardUnSubscribeResponse" +
            "")]
        System.Threading.Tasks.Task updateLandlordCardUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateLandlordCardCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IUpdateLandlordCard/UpdateLandlordCard_Client")]
        void UpdateLandlordCard_Client(DoudizhuClient.DoudizhuService.Player landlord, string cardsType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateLandlordCardChannel : DoudizhuClient.DoudizhuService.IUpdateLandlordCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateLandlordCardClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IUpdateLandlordCard>, DoudizhuClient.DoudizhuService.IUpdateLandlordCard {
        
        public UpdateLandlordCardClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UpdateLandlordCardClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UpdateLandlordCardClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateLandlordCardClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateLandlordCardClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void updateLandlordCardSubscribe(int roomNumber) {
            base.Channel.updateLandlordCardSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateLandlordCardSubscribeAsync(int roomNumber) {
            return base.Channel.updateLandlordCardSubscribeAsync(roomNumber);
        }
        
        public void updateLandlordCardUnSubscribe(int roomNumber) {
            base.Channel.updateLandlordCardUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateLandlordCardUnSubscribeAsync(int roomNumber) {
            return base.Channel.updateLandlordCardUnSubscribeAsync(roomNumber);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DoudizhuServiceContract", ConfigurationName="DoudizhuService.IUpdateChatter", CallbackContract=typeof(DoudizhuClient.DoudizhuService.IUpdateChatterCallback))]
    public interface IUpdateChatter {
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateChatter/updateChatterSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateChatter/updateChatterSubscribeResponse")]
        void updateChatterSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateChatter/updateChatterSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateChatter/updateChatterSubscribeResponse")]
        System.Threading.Tasks.Task updateChatterSubscribeAsync(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateChatter/updateChatterUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateChatter/updateChatterUnSubscribeResponse")]
        void updateChatterUnSubscribe(int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="DoudizhuServiceContract/IUpdateChatter/updateChatterUnSubscribe", ReplyAction="DoudizhuServiceContract/IUpdateChatter/updateChatterUnSubscribeResponse")]
        System.Threading.Tasks.Task updateChatterUnSubscribeAsync(int roomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateChatterCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="DoudizhuServiceContract/IUpdateChatter/UpdateChatter_Client")]
        void UpdateChatter_Client(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateChatterChannel : DoudizhuClient.DoudizhuService.IUpdateChatter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateChatterClient : System.ServiceModel.DuplexClientBase<DoudizhuClient.DoudizhuService.IUpdateChatter>, DoudizhuClient.DoudizhuService.IUpdateChatter {
        
        public UpdateChatterClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UpdateChatterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UpdateChatterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateChatterClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateChatterClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void updateChatterSubscribe(int roomNumber) {
            base.Channel.updateChatterSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateChatterSubscribeAsync(int roomNumber) {
            return base.Channel.updateChatterSubscribeAsync(roomNumber);
        }
        
        public void updateChatterUnSubscribe(int roomNumber) {
            base.Channel.updateChatterUnSubscribe(roomNumber);
        }
        
        public System.Threading.Tasks.Task updateChatterUnSubscribeAsync(int roomNumber) {
            return base.Channel.updateChatterUnSubscribeAsync(roomNumber);
        }
    }
}
